<?php
/**
 * CaptureTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Klarna\OrderManagement
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Klarna Order Managment API
 *
 * API to handle order lifecycle
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Klarna\OrderManagement;

use PHPUnit\Framework\TestCase;

/**
 * CaptureTest Class Doc Comment
 *
 * @category    Class
 * @description Capture
 * @package     Klarna\OrderManagement
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CaptureTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Capture"
     */
    public function testCapture()
    {
    }

    /**
     * Test attribute "capture_id"
     */
    public function testPropertyCaptureId()
    {
    }

    /**
     * Test attribute "reference"
     */
    public function testPropertyReference()
    {
    }

    /**
     * Test attribute "klarna_reference"
     */
    public function testPropertyKlarnaReference()
    {
    }

    /**
     * Test attribute "captured_amount"
     */
    public function testPropertyCapturedAmount()
    {
    }

    /**
     * Test attribute "captured_at"
     */
    public function testPropertyCapturedAt()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "order_lines"
     */
    public function testPropertyOrderLines()
    {
    }

    /**
     * Test attribute "refunded_amount"
     */
    public function testPropertyRefundedAmount()
    {
    }

    /**
     * Test attribute "billing_address"
     */
    public function testPropertyBillingAddress()
    {
    }

    /**
     * Test attribute "shipping_address"
     */
    public function testPropertyShippingAddress()
    {
    }

    /**
     * Test attribute "shipping_info"
     */
    public function testPropertyShippingInfo()
    {
    }
}
