<?php
/**
 * CaptureObjectTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Klarna\OrderManagement
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Klarna Order Managment API
 *
 * API to handle order lifecycle
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Klarna\OrderManagement;

use PHPUnit\Framework\TestCase;

/**
 * CaptureObjectTest Class Doc Comment
 *
 * @category    Class
 * @description CaptureObject
 * @package     Klarna\OrderManagement
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CaptureObjectTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CaptureObject"
     */
    public function testCaptureObject()
    {
    }

    /**
     * Test attribute "captured_amount"
     */
    public function testPropertyCapturedAmount()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "reference"
     */
    public function testPropertyReference()
    {
    }

    /**
     * Test attribute "order_lines"
     */
    public function testPropertyOrderLines()
    {
    }

    /**
     * Test attribute "shipping_info"
     */
    public function testPropertyShippingInfo()
    {
    }

    /**
     * Test attribute "shipping_delay"
     */
    public function testPropertyShippingDelay()
    {
    }
}
