<?php
/**
 * SelectedShippingOptionDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Klarna\OrderManagement
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Klarna Order Managment API
 *
 * API to handle order lifecycle
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Klarna\OrderManagement;

use PHPUnit\Framework\TestCase;

/**
 * SelectedShippingOptionDtoTest Class Doc Comment
 *
 * @category    Class
 * @description SelectedShippingOptionDto
 * @package     Klarna\OrderManagement
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SelectedShippingOptionDtoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SelectedShippingOptionDto"
     */
    public function testSelectedShippingOptionDto()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "tms_reference"
     */
    public function testPropertyTmsReference()
    {
    }

    /**
     * Test attribute "carrier"
     */
    public function testPropertyCarrier()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "method"
     */
    public function testPropertyMethod()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "tax_amount"
     */
    public function testPropertyTaxAmount()
    {
    }

    /**
     * Test attribute "tax_rate"
     */
    public function testPropertyTaxRate()
    {
    }

    /**
     * Test attribute "location"
     */
    public function testPropertyLocation()
    {
    }

    /**
     * Test attribute "timeslot"
     */
    public function testPropertyTimeslot()
    {
    }

    /**
     * Test attribute "carrier_product"
     */
    public function testPropertyCarrierProduct()
    {
    }

    /**
     * Test attribute "selected_addons"
     */
    public function testPropertySelectedAddons()
    {
    }

    /**
     * Test attribute "class"
     */
    public function testPropertyClass()
    {
    }
}
