<?php
/**
 * ShippingInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Klarna\OrderManagement
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Klarna Order Managment API
 *
 * API to handle order lifecycle
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Klarna\OrderManagement;

use PHPUnit\Framework\TestCase;

/**
 * ShippingInfoTest Class Doc Comment
 *
 * @category    Class
 * @description ShippingInfo
 * @package     Klarna\OrderManagement
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ShippingInfoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ShippingInfo"
     */
    public function testShippingInfo()
    {
    }

    /**
     * Test attribute "shipping_company"
     */
    public function testPropertyShippingCompany()
    {
    }

    /**
     * Test attribute "shipping_method"
     */
    public function testPropertyShippingMethod()
    {
    }

    /**
     * Test attribute "tracking_number"
     */
    public function testPropertyTrackingNumber()
    {
    }

    /**
     * Test attribute "tracking_uri"
     */
    public function testPropertyTrackingUri()
    {
    }

    /**
     * Test attribute "return_shipping_company"
     */
    public function testPropertyReturnShippingCompany()
    {
    }

    /**
     * Test attribute "return_tracking_number"
     */
    public function testPropertyReturnTrackingNumber()
    {
    }

    /**
     * Test attribute "return_tracking_uri"
     */
    public function testPropertyReturnTrackingUri()
    {
    }
}
