<?php
/**
 * TimeslotTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Klarna\OrderManagement
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Klarna Order Managment API
 *
 * API to handle order lifecycle
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Klarna\OrderManagement;

use PHPUnit\Framework\TestCase;

/**
 * TimeslotTest Class Doc Comment
 *
 * @category    Class
 * @description Timeslot
 * @package     Klarna\OrderManagement
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class TimeslotTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Timeslot"
     */
    public function testTimeslot()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "start"
     */
    public function testPropertyStart()
    {
    }

    /**
     * Test attribute "end"
     */
    public function testPropertyEnd()
    {
    }

    /**
     * Test attribute "cutoff"
     */
    public function testPropertyCutoff()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }
}
